version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
    commit-message:
      prefix: ""
      prefix-development: ""
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
